name: CD

on:
  workflow_dispatch:

permissions:
  contents: write  # Required for pushing tags and creating GitHub releases

jobs:
  release:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --local user.name "GitHub Actions Bot"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      # Read current version from podspec
      - name: Read Current Version
        id: version
        run: |
          CURRENT_VERSION=$(grep -m 1 "s.version" Imprint.podspec | sed -E "s/.*= *[\'\"](([0-9]+\.){2}[0-9]+)[\'\"].*/\1/")
          echo "Using version from podspec: $CURRENT_VERSION"
          echo "new_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      # Generate changelog from commits since last tag
      - name: Generate Changelog
        id: changelog
        run: |
          set +x
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          
          if [ -z "$PREVIOUS_TAG" ]; then
            echo "No previous tag found; using full history"
            CHANGELOG=$(git log --pretty=format:"- %s (%h)" --no-merges)
          else
            echo "Generating changelog since $PREVIOUS_TAG"
            CHANGELOG=$(git log ${PREVIOUS_TAG}..HEAD --pretty=format:"- %s (%h)" --no-merges)
          fi

          FEATURES=$(echo "$CHANGELOG" | grep -i "feat\|feature" || echo "")
          FIXES=$(echo "$CHANGELOG" | grep -i "fix\|bug" || echo "")
          IMPROVEMENTS=$(echo "$CHANGELOG" | grep -i "improve\|enhance\|refactor\|perf" || echo "")
          OTHERS=$(echo "$CHANGELOG" | grep -v -i "feat\|feature\|add\|fix\|bug\|issue\|improve\|enhance\|refactor\|perf" || echo "")

          {
            echo "changelog<<CHANGELOG_EOF"
            echo "## What's Changed in v${{ steps.version.outputs.new_version }}"
            echo ""

            if [ -n "$FEATURES" ]; then
              echo "### New Features"
              echo "$FEATURES"
              echo ""
            fi

            if [ -n "$FIXES" ]; then
              echo "### Bug Fixes"
              echo "$FIXES"
              echo ""
            fi

            if [ -n "$IMPROVEMENTS" ]; then
              echo "### Improvements"
              echo "$IMPROVEMENTS"
              echo ""
            fi

            if [ -n "$OTHERS" ]; then
              echo "### Other Changes"
              echo "$OTHERS"
              echo ""
            fi

            echo "CHANGELOG_EOF"
          } >> $GITHUB_OUTPUT

      # Create and push git tag
      - name: Create Git Tag
        run: |
          set +x
          NEW_VERSION=${{ steps.version.outputs.new_version }}
          git tag $NEW_VERSION
          git push origin $NEW_VERSION

      # Publish to CocoaPods
      - name: Publish to CocoaPods
        run: |
          set +x
          pod trunk push Imprint.podspec --allow-warnings --silent

      # Create GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.new_version }}
          name: Release ${{ steps.version.outputs.new_version }}
          body: ${{ steps.changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Clean up
      - name: Clean up
        if: always()
        run: |
          rm -rf ~/Library/Developer/Xcode/DerivedData/Imprint-*
          rm -rf ~/Library/Caches/org.carthage.CarthageKit
          rm -rf ~/Library/Caches/CocoaPods