name: CI

on:
  push:
    branches: [main]
  pull_request:

# Add permissions restriction
permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

       # Set timeout to prevent long-running jobs from hogging resources
      - name: Checkout SDK Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1  # Limit git history to reduce exposure
          persist-credentials: false  # Don't persist GitHub credentials
      
      # Build SDK Source Files
      - name: Build SDK
        run: |
          xcodebuild clean build -project Imprint.xcodeproj -scheme Imprint -destination "platform=iOS Simulator,name=iPhone 14,OS=17.2" -verbose | xcpretty

      # Run Unit Tests
      - name: Run Unit Tests
        run: |
          xcodebuild test -project Imprint.xcodeproj -scheme Imprint -destination "platform=iOS Simulator,name=iPhone 14,OS=17.2" -enableCodeCoverage NO -verbose | xcpretty

      # Update Podfile to use local SDK
      - name: Update Podfile to use local SDK
        working-directory: ImprintDemo/Cocoapods
        run: |
          set +x
          # Create a temporary Podfile that references the local SDK
          cat > Podfile.tmp << EOF
          platform :ios, '15.0'

          target 'ImprintDemo' do
            # Comment the next line if you don't want to use dynamic frameworks
            use_frameworks!

            pod 'Imprint', :path => '../../'
            
          end
          EOF
          
          # Replace the original Podfile
          mv Podfile.tmp Podfile

      # Test Demo App with CocoaPods Integration
      - name: Install Pods for Demo App
        working-directory: ImprintDemo/Cocoapods
        run: |
          pod install --no-repo-update

      - name: Build Demo App via CocoaPods
        working-directory: ImprintDemo
        run: |
          xcodebuild clean build -workspace ImprintDemo.xcworkspace -scheme ImprintDemo -destination "platform=iOS Simulator,name=iPhone 14,OS=17.2" | grep -v "sensitive" | xcpretty

      # Dynamically Add Local SDK as SwiftPM Dependency
      - name: Patch Swift Package to use local path
        working-directory: ImprintDemo/SPM/ImprintDemo.xcodeproj
        run: |
          echo "Patching .pbxproj to replace remote SDK with local path"

          # Remove repositoryURL line
          sed -i '' '/XCRemoteSwiftPackageReference "imprint-sdk-ios"/,/};/s|repositoryURL = .*;||' project.pbxproj

          # Remove requirement block (3-line structure)
          sed -i '' '/XCRemoteSwiftPackageReference "imprint-sdk-ios"/,/};/{
            /requirement = {/,/};/d
          }' project.pbxproj

          # Add path = "../../"; just after isa line
          sed -i '' '/XCRemoteSwiftPackageReference "imprint-sdk-ios"/,/};/{
            /isa = XCRemoteSwiftPackageReference;/a\
            \ \ \ \ path = "../../";
          }' project.pbxproj

      - name: Print Patched SDK Block
        working-directory: ImprintDemo/SPM/ImprintDemo.xcodeproj
        run: |
          grep -A 5 'XCRemoteSwiftPackageReference "imprint-sdk-ios"' project.pbxproj

      # Build Demo App
      - name: Build Demo App via SwiftPM
        working-directory: ImprintDemo/SPM
        run: |
          xcodebuild clean build \
            -project ImprintDemo.xcodeproj \
            -scheme ImprintDemo \
            -destination "platform=iOS Simulator,name=iPhone 14,OS=17.2" | xcpretty
          
      # Clean up workspace
      - name: Clean up
        if: always()
        run: |
          set +x
          rm -rf ~/Library/Developer/Xcode/DerivedData/Imprint-*
          rm -rf ~/Library/Caches/CocoaPods