name: Build & Test

on:
  push:
    branches: [main, main-*, release, release-*]
  pull_request:

jobs:
  build_and_test:
    uses: ./.github/workflows/fastlane.yml
    with:
      lane: test
    secrets: inherit
