name: CI

on:
  push:
    branches: [main]
  pull_request:

# Add permissions restriction
permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

       # Set timeout to prevent long-running jobs from hogging resources
      - name: Checkout SDK Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1  # Limit git history to reduce exposure
          persist-credentials: false  # Don't persist GitHub credentials
      
      # Build SDK Source Files
      - name: Build SDK
        run: |
          xcodebuild clean build -project Imprint.xcodeproj -scheme Imprint -destination "platform=iOS Simulator,name=iPhone 14,OS=17.2" -verbose | xcpretty

      # Run Unit Tests
      - name: Run Unit Tests
        run: |
          xcodebuild test -project Imprint.xcodeproj -scheme Imprint -destination "platform=iOS Simulator,name=iPhone 14,OS=17.2" -enableCodeCoverage NO -verbose | xcpretty

      # Update Podfile to use local SDK
      - name: Update Podfile to use local SDK
        working-directory: ImprintDemo
        run: |
          set +x
          # Create a temporary Podfile that references the local SDK
          cat > Podfile.tmp << EOF
          platform :ios, '15.0'

          target 'ImprintDemo' do
            # Comment the next line if you don't want to use dynamic frameworks
            use_frameworks!

            pod 'Imprint', :path => '../'
            
          end
          EOF
          
          # Replace the original Podfile
          mv Podfile.tmp Podfile

      # Test Demo App with CocoaPods Integration
      - name: Install Pods for Demo App
        working-directory: ImprintDemo
        run: |
          pod install --no-repo-update

      - name: Build Demo App via CocoaPods
        working-directory: ImprintDemo
        run: |
          xcodebuild clean build -workspace ImprintDemo.xcworkspace -scheme ImprintDemo -destination "platform=iOS Simulator,name=iPhone 14,OS=17.2" | grep -v "sensitive" | xcpretty

      # Test Swift Package Manager Integration
      - name: Create Temporary SPM Demo App
        run: |
          mkdir ImprintSPMDemo
          cd ImprintSPMDemo
          
          # Create Package.swift
          cat > Package.swift <<EOF
          // swift-tools-version:5.7
          import PackageDescription

          let package = Package(
              name: "ImprintSPMDemo",
              platforms: [
                  .iOS(.v15)
              ],
              dependencies: [
                  .package(path: "../") // Local path to your SDK
              ],
              targets: [
                  .executableTarget(
                      name: "ImprintSPMDemo",
                      dependencies: ["Imprint"]
                  )
              ]
          )
          EOF

          mkdir Sources
          mkdir Sources/ImprintSPMDemo

          # Create a minimal main.swift
          cat > Sources/ImprintSPMDemo/main.swift <<EOF
          import Imprint

          print("SPM Demo App Compiled Successfully!")
          EOF

      - name: Build Temporary SPM Demo App
        working-directory: ImprintSPMDemo
        run: |
          swift build
          
      # Clean up workspace
      - name: Clean up
        if: always()
        run: |
          set +x
          rm -rf ~/Library/Developer/Xcode/DerivedData/Imprint-*
          rm -rf ~/Library/Caches/CocoaPods